package auth

import (
	"sync"
	"time"
)

// Session represents an authenticated user's server-side session.
//
// KEK (Key Encryption Key) is the user's master symmetric key, held in memory
// for the lifetime of the session and used to decrypt per-record data keys on
// demand. It is never persisted to disk — losing the session (restart, expiry,
// logout) means the KEK must be re-derived from the user's password.
type Session struct {
	UserID    string
	KEK       []byte
	ExpiresAt time.Time
}

// SessionStore is an in-memory, goroutine-safe store that maps opaque session
// tokens to their corresponding Session. Because the KEK lives only in memory,
// all sessions are lost on process restart and clients must re-authenticate.
//
// Expired sessions are evicted lazily on Get; no background sweeper is run.
// For production use, consider adding a periodic cleanup goroutine to bound
// unbounded memory growth from abandoned (never-deleted) sessions.
type SessionStore struct {
	mu       sync.RWMutex
	sessions map[string]*Session
}

// NewSessionStore returns an empty, ready-to-use SessionStore.
func NewSessionStore() *SessionStore {
	return &SessionStore{
		sessions: make(map[string]*Session),
	}
}

// Save stores session under the given token, overwriting any prior value.
// The token is assumed to be a cryptographically random value generated by
// the caller — SessionStore does not validate or generate tokens itself.
func (s *SessionStore) Save(token string, session *Session) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.sessions[token] = session
}

// Get returns the Session for the given token and true if the token exists and
// has not yet expired. Returns (nil, false) for both unknown tokens and expired
// ones, intentionally giving callers no way to distinguish the two cases —
// this avoids leaking whether a token ever existed.
//
// Note: the expired entry is not removed here to keep the read path lock-free
// at the cost of leaving stale entries in the map until Delete is called or
// the process restarts.
func (s *SessionStore) Get(token string) (*Session, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	session, ok := s.sessions[token]
	if !ok {
		return nil, false
	}
	if time.Now().After(session.ExpiresAt) {
		return nil, false
	}
	return session, true
}

// Delete removes the session associated with token, releasing the in-memory
// KEK. It is a no-op if the token does not exist. Should be called on logout
// and is the primary mechanism for explicit session invalidation.
func (s *SessionStore) Delete(token string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.sessions, token)
}