package local

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Kyei-Ernest/DocOps/models"
)

// LocalConnector stores files on the local filesystem.
// basePath is the root directory where all files are written.
// It is set once at startup from config and never changes.
type LocalConnector struct {
	basePath string
}

// New creates a new LocalConnector rooted at basePath.
// If the directory does not exist it is created — including
// any missing parent directories. This is safe to call even
// if the directory already exists.
func New(basePath string) (*LocalConnector, error) {
	// 0755 means: owner can read/write/execute,
	// group and others can read/execute — standard for directories
	if err := os.MkdirAll(basePath, 0755); err != nil {
		return nil, fmt.Errorf("failed to create storage directory %q: %w", basePath, err)
	}

	return &LocalConnector{basePath: basePath}, nil
}

// Upload writes the file stream from r.Content to disk.
// The file is written to basePath/key — the key is a UUID
// generated by the upload handler before calling this.
//
// Critical: we never load the full file into memory.
// io.Copy streams bytes from r.Content directly into the file
// in chunks — constant memory usage regardless of file size.
func (c *LocalConnector) Upload(ctx context.Context, r models.UploadRequest) (models.FileRef, error) {
	// build the full path: basePath + OS separator + key
	// filepath.Join handles OS differences automatically
	// (backslash on Windows, forward slash on Unix)
	fullPath := filepath.Join(c.basePath, r.Key)

	// create the file — if a file with this key already exists
	// os.Create truncates it, which is fine because keys are UUIDs
	file, err := os.Create(fullPath)
	if err != nil {
		return models.FileRef{}, fmt.Errorf("failed to create file at %q: %w", fullPath, err)
	}
	// always close the file when this function returns
	// even if an error occurs below
	defer file.Close()

	// stream bytes from the request content into the file
	// io.Copy returns the number of bytes written
	written, err := io.Copy(file, r.Content)
	if err != nil {
		// if the copy fails partway through, remove the
		// incomplete file so we don't leave junk on disk
		os.Remove(fullPath)
		return models.FileRef{}, fmt.Errorf("failed to write file content: %w", err)
	}

	// return a reference describing what was stored
	return models.FileRef{
		Key:         r.Key,
		SizeBytes:   written,
		ContentType: r.ContentType,
	}, nil
}

// Download opens the file at basePath/key and returns it
// as an io.ReadCloser so the caller can stream it directly
// into the HTTP response without loading it into memory.
//
// IMPORTANT: the caller is responsible for calling Close()
// on the returned ReadCloser when done. In the download
// handler this should be deferred immediately.
func (c *LocalConnector) Download(ctx context.Context, key string) (io.ReadCloser, error) {
	fullPath := filepath.Join(c.basePath, key)

	file, err := os.Open(fullPath)
	if err != nil {
		// os.IsNotExist gives a clear signal to the handler
		// to return a 404 rather than a 500
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("file not found: %s", key)
		}
		return nil, fmt.Errorf("failed to open file %q: %w", fullPath, err)
	}

	// return the open file directly — *os.File implements
	// io.ReadCloser so no wrapping needed
	return file, nil
}

// Delete removes the file at basePath/key from disk.
// It also removes the file from the metadata store —
// that is handled by the delete handler, not here.
// This function only touches the filesystem.
func (c *LocalConnector) Delete(ctx context.Context, key string) error {
	fullPath := filepath.Join(c.basePath, key)

	err := os.Remove(fullPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("file not found: %s", key)
		}
		return fmt.Errorf("failed to delete file %q: %w", fullPath, err)
	}

	return nil
}

// Ping checks that the base storage directory is accessible.
// Called at startup to verify the connector is healthy before
// the server starts accepting requests.
func (c *LocalConnector) Ping(ctx context.Context) error {
	_, err := os.Stat(c.basePath)
	if err != nil {
		return fmt.Errorf("storage directory %q is not accessible: %w", c.basePath, err)
	}
	return nil
}
