// models/storage.go
package models

import "io"

type UploadRequest struct {
    Key         string        // the UUID storage key — generated by handler
    Content     io.Reader     // file stream — never fully buffered
    ContentType string        // e.g. "application/pdf"
    SizeBytes   int64
}

type FileRef struct {
    Key         string
    SizeBytes   int64
    ContentType string
}